### ISSUE TITLE
pull하는 경우에 발생하는 충돌

### ISSUE THREAD

**Issue by minjeongss** [JeongHyunJi/GameMaking#2]
GitDesktop을 이용해 Pull을 하는 경우, 충돌이 종종 발생함.
Pull을 눌렀을 때 충돌이 발생한다는 것만 제시되고 그 이상을 진행하지 못함.
취소 버튼만 존재함.

**Comment by minjeongss** [comment]
### commit을 한 경우
1. commit을 먼저 진행한다.
2. Git Bash 또는 Prompt창을 Open한다.
창에서 다음과 같이 입력한다.
+ git log
+ git reset --hard (돌아가기를 해당하는 시점의 log)
3. commit 창에 존재하던 것들이 사라져 있는 동시에 바로 Pull이 가능하다.

### commit을 하지 않은 경우
1. Git Bash 또는 Prompt창을 Open
2. git reset --hard (돌아가기를 희망하는 시점의 log)
3. commit 창에 존재하던 것들이 사라져 pull을 해도 충돌이 발생하지 않음

**Comment by minjeongss** [comment]
단, git reset에서 hard를 하지 않으면 제대로 작동되지 않는 경우가 존재함.

**Comment by jeonghyun06** [comment]
sourcetree 사용중 되돌리는 경우 git clean -d -f -f 를 통해 변경사항을 모두 삭제한 후 pull 하면 쉽게 되돌릴 수 있음.
